### ISSUE TITLE
8051 support

### ISSUE THREAD

**Issue by kimstik** [rizinorg/jsdec#7]
cutter 2.0.2 shows "8051 is not currently supported."
Is it possible to add it?

**Comment by wargio** [comment]
i guess so. can you reference here the ISA documents?

**Comment by wargio** [comment]
It's now in my TODO list, thank you for the help with the docs!

**Comment by wargio** [comment]
this will probably be available from 0.3.0, but if you want to try/use it you can manually install these 2 file:
- update `libdec/archs.js` with https://raw.githubusercontent.com/rizinorg/jsdec/master/libdec/archs.js
- copy under `libdec/arch/` this new file https://raw.githubusercontent.com/rizinorg/jsdec/master/libdec/arch/8051.js

**Comment by kimstik** [comment]
Thanks! it works!
